### ISSUE TITLE
Build fails if edgeConfigs/api directory is missing

### ISSUE THREAD

**Issue by gagangrewal** [apigee/apigee-config-maven-plugin#37]
For the below directory structure

|── {proxyName}
|   |  ├── apiproxy
|   |  ├── edgeConfigs
|   |   |   |   ├── api
|   |   |   |   ├── env

If directory {proxyName}/edgeConfigs/api is missing, below exception is thrown. Ideally, this directory should be skipped if not present.

**WORKAROUND**: Empty directory(api) can be created in edgeConfigs to prevent this exception.

`[ERROR] Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.2:kvms (create-config-kvm) on project {proxyName}: null: MojoExecutionException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.apigee.edge.config:apigee-config-maven-plugin:1.2:kvms (create-config-kvm) on project {proxyName}: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
        at com.apigee.edge.config.mavenplugin.GatewayAbstractMojo.getAPIList(GatewayAbstractMojo.java:374)
        at com.apigee.edge.config.mavenplugin.KVMMojo.execute(KVMMojo.java:359)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
`

**Comment by seymen** [comment]
Also empty directories cannot be committed to git by default. Therefore when a project is cloned in another machine, deployment will fail as the clone won't have the api folder.

I've been adding an empty dotfile under api folder and commit that as a workaround.

**Comment by ssvaidyanathan** [comment]
@gagangrewal - I removed my api directory and see no error

```
[INFO] Retrieving API list from resources/edge/api
[INFO] No API scoped KVM config found.
```
